# Generated by Django 6.0.3 on 2026-03-31 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_rename_fecha_cita_fecha_cita_cita_clinica_and_more'),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='cita',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='atencion_medica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.atencionmedica'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='dosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='medicamento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='nombre_tratamiento',
            field=models.CharField(default='Tratamiento general', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
