# Generated by Django 6.0.3 on 2026-04-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
            ],
        ),
    ]
