# Generated by Django 6.0.3 on 2026-03-31 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('mascotas', '0003_alimentacion_fecha_registro_mascota_alergias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='fecha',
            new_name='fecha_cita',
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('tipo_atencion', models.CharField(max_length=100)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento_indicado', models.TextField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('clinica', models.CharField(blank=True, max_length=120, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
