# Generated by Django 6.0.3 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_rename_fecha_cita_fecha_cita_cita_clinica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atencionmedica",
            name="examenes_ordenados",
            field=models.TextField(blank=True, null=True),
        ),
    ]
